//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Messages
{
    [Serializable]
    public class JointStatesMsg : Message
    {
        public const string k_RosMessageName = "Messages/JointStates";
        public override string RosMessageName => k_RosMessageName;

        public short j1;
        public short j2;
        public short j3;
        public short j4;
        public short j5;
        public short j6;

        public JointStatesMsg()
        {
            this.j1 = 0;
            this.j2 = 0;
            this.j3 = 0;
            this.j4 = 0;
            this.j5 = 0;
            this.j6 = 0;
        }

        public JointStatesMsg(short j1, short j2, short j3, short j4, short j5, short j6)
        {
            this.j1 = j1;
            this.j2 = j2;
            this.j3 = j3;
            this.j4 = j4;
            this.j5 = j5;
            this.j6 = j6;
        }

        public static JointStatesMsg Deserialize(MessageDeserializer deserializer) => new JointStatesMsg(deserializer);

        private JointStatesMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.j1);
            deserializer.Read(out this.j2);
            deserializer.Read(out this.j3);
            deserializer.Read(out this.j4);
            deserializer.Read(out this.j5);
            deserializer.Read(out this.j6);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.j1);
            serializer.Write(this.j2);
            serializer.Write(this.j3);
            serializer.Write(this.j4);
            serializer.Write(this.j5);
            serializer.Write(this.j6);
        }

        public override string ToString()
        {
            return "JointStatesMsg: " +
            "\nj1: " + j1.ToString() +
            "\nj2: " + j2.ToString() +
            "\nj3: " + j3.ToString() +
            "\nj4: " + j4.ToString() +
            "\nj5: " + j5.ToString() +
            "\nj6: " + j6.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
